### ISSUE TITLE
Missing Event ID's 9, 14, 16, and 255 

### ISSUE THREAD

**Issue by AndrewRathbun** [sbousseaden/EVTX-SAMPLES#16]
Greetings! Thank you so much for providing all these samples. I've been looking to map out all Sysmon events for EvtxECmd for a while and this provides almost every event ID I need to complete that! I parsed the entire directory of the evtx files in this repo and it appears event ID's 9, 14, 16, and 255 (not quite as important as it's a Sysmon error event) are not present in any of these logs. Full list here: https://docs.microsoft.com/en-us/sysinternals/downloads/sysmon#events. 

Is there any chance you can keep a casual eye out for those events in any future logs you come across in your travels? I'd appreciate it for the purpose of my research. Here's a visual of what I'm seeing on my end. 

![image](https://user-images.githubusercontent.com/36825567/100517835-b990ed80-315b-11eb-9e26-eee98dc41def.png)

Thanks again for your work!

**Comment by Samirbous** [comment]
Hi Andrew, thanks! for your question events 9, 14 and 16 are not recorded since never tested an attack technique or tool that matched on those events (registry key rename operation or disk raw access are quite corner changes), but If I encounter a TTP that does so will let you know.

**Comment by sbousseaden** [comment]
Hi Andrew, thanks! for your question events 9, 14 and 16 are not recorded since never tested an attack technique or tool that matched on those events (registry key rename operation or disk raw access are quite corner changes), but If I encounter a TTP that does so will let you know.  Also usually if the event_id is relevant to the trace collection I added it to the evtx name (e.g. sysmon_1_11_16_something.evtx can be useful for grep without parsing ...)

**Comment by AndrewRathbun** [comment]
Very helpful. I appreciate you making these available. I've since mapped out all events that I could for EvtxECmd and will wrap up the rest of the Sysmon events when/if those come about. Cheers!
